### ISSUE TITLE
Add Tutorial

### ISSUE THREAD

**Issue by SusanSuY** [Chaozs/Frostbite#5]
Add the whole beginning part with the camp, which includes:
- "F" button appears on screen when player gets close to interactable object (teaches them how to interact with objects); this only happens in tutorial stage (the beginning)
- Skeletal remains of last guy who died to yeti
- The guy's diary with context to the game (controls/rules/backstory)
- Torch next to the guy that player can pick up to use
- Lighter next to the guy which player picks up to use
- Some cloth next to the guy (starting amount of cloth)

**Comment by PrakharJalan** [comment]
- Spoke with the prof, we can just shift the tutorial into a README. Game will just start off with the scene
